export class ResManager {
  // 颜色
  static EC_MAIN_COLOR = "#00C4B3"
  static EC_SUB_BLUE = "#0698FF"
  static EC_SUB_GREEN = "#27BA9B"
  static EC_SUB_YELLOW = "#FFAB2E"
  static EC_SUB_RED = "#E34D59"
  static EC_MID_19 = "#191919"
  static EC_MID_59 = "#595959"
  static EC_MID_99 = "#999999"
  static EC_MID_WHITE = "#ffffff"
  static EC_MID_BLACK = "#000"
  static EC_MID_BG = "#F7F6F9"
  static EC_MID_LINE = "#E8E8E8"
  // 字体
  static EC_VP_TEN = "10vp"
  static EC_CONTENT_SPACE = "15vp"
  static EC_MICRO_FS = "10fp"
  static EC_BIG_TITLE_FS = "24fp"
  static EC_PAGE_TITLE_FS = "20fp"
  static EC_MODULE_TITLE_FS = "16fp"
  static EC_NORMAL_FS = "14fp"
  static EC_ARD_FONT_SIZE = "13fp"
  static EC_SMALL_FS = "12fp"
  static EC_NORMAL_RD = "8vp"
  // 图片
  static BTN_CLEAN = '' // $r('app.media.btn_clean')
  static IC_ARROW_LEFT = '' // $r('app.media.ic_arrow_left')
  static IC_ARROW_RIGHT = '' // $r('app.media.ic_arrow_right')
  static IC_DOWN = '' // $r('app.media.ic_down')
  static IC_ZWNR = '' // $r("app.media.ic_zwnr")
  static IMG_FAIL = '' // $r('app.media.img_fail')
  static IMG_SUCCESS = '' // $r('app.media.img_success')
  static PAGE_LOADING = '' // $r('app.media.page_loading')
  // 间距
  static SIZE_GUTTER_LG = 15
  static SIZE_GUTTER_MD = 10
  static SIZE_GUTTER_SM = 5
}
