export class ResManager {
  // 颜色
  static EC_MAIN_COLOR = $r('app.color.ec_main_color')
  static EC_SUB_BLUE = $r('app.color.ec_sub_blue')
  static EC_SUB_GREEN = $r('app.color.ec_sub_green')
  static EC_SUB_YELLOW = $r('app.color.ec_sub_yellow')
  static EC_SUB_RED = $r('app.color.ec_sub_red')
  static EC_MID_19 = $r('app.color.ec_mid_19')
  static EC_MID_59 = $r('app.color.ec_mid_59')
  static EC_MID_99 = $r('app.color.ec_mid_99')
  static EC_MID_WHITE = $r('app.color.ec_mid_white')
  static EC_MID_BLACK = $r('app.color.ec_mid_black')
  static EC_MID_BG = $r('app.color.ec_mid_bg')
  static EC_MID_LINE = $r('app.color.ec_mid_line')
  // 字体
  static EC_VP_TEN = $r('app.float.ec_vp_ten')
  static EC_CONTENT_SPACE = $r('app.float.ec_content_space')
  static EC_MICRO_FS = $r('app.float.ec_micro_font_size')
  static EC_BIG_TITLE_FS = $r('app.float.ec_big_title_font_size')
  static EC_PAGE_TITLE_FS = $r('app.float.ec_page_title_font_size')
  static EC_MODULE_TITLE_FS = $r('app.float.ec_module_title_font_size')
  static EC_NORMAL_FS = $r('app.float.ec_normal_font_size')
  static EC_ARD_FONT_SIZE = $r('app.float.ec_ard_font_size')
  static EC_SMALL_FS = $r('app.float.ec_small_font_size')
  static EC_NORMAL_RD = $r('app.float.ec_normal_radius')
  // 图片
  static BTN_CLEAN = $r('app.media.btn_clean')
  static IC_ARROW_LEFT = $r('app.media.ic_arrow_left')
  static IC_ARROW_RIGHT = $r('app.media.ic_arrow_right')
  static IC_DOWN = $r('app.media.ic_down')
  static IC_ZWNR = $r("app.media.ic_zwnr")
  static IMG_FAIL = $r('app.media.img_fail')
  static IMG_SUCCESS = $r('app.media.img_success')
  static PAGE_LOADING = $r('app.media.page_loading')
  // 间距
  static SIZE_GUTTER_LG = 15
  static SIZE_GUTTER_MD = 10
  static SIZE_GUTTER_SM = 5
}
